[job]
dump_folder = "TODO"
description = "benchmark"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 1000000000
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
disable_console_log = true

[model]
name = "llama3"
flavor = "ado1b"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = ""

[optimizer]
name = "AdamW"
lr = 0.001
fused = true

[lr_scheduler]
warmup_steps = 0
decay_ratio = 0.1
decay_type = "linear"

[training]
batch_size = 512
seq_len = 1024
max_norm = 1.0  # grad norm clipping
steps = 60000
compile = true
dataset = ""
seed = 1234
add_bos = false
add_eos = true
tokenizer = "EleutherAI/gpt-neox-20b"

[parallelism]
data_parallel_replicate_degree = 2
data_parallel_shard_degree = -1 
tensor_parallel_degree = 1
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval = 9999999
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]
keep_latest_k = 0

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[comm]
init_timeout_seconds = 600
train_timeout_seconds = 600 # very high timeout for mixtera ops, temp solution, should parallelize some things e.g. fitting of scaling laws